I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    $ inventory.add_item(mana_rum, 99)
  File "game/script.rpy", line 28, in <module>
    $ inventory.add_item(mana_rum, 99)
NameError: name 'mana_rum' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    $ inventory.add_item(mana_rum, 99)
  File "C:\Users\Sanzid\Desktop\Renpy\renpy-8.1.0-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Sanzid\Desktop\Renpy\renpy-8.1.0-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 28, in <module>
    $ inventory.add_item(mana_rum, 99)
NameError: name 'mana_rum' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.0.23051307
Advanced inventory 1.0
Wed Aug  9 02:46:24 2023
